services:
  weight:
    image: weight-api
    container_name: weightapi
    build:
      context: ../WeightMicroservice
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    depends_on:
      - db-weight
    env_file:
      - local.env
  user:
    image: user-api
    container_name: userapi
    build:
      context: ../UserMicroservice
      dockerfile: Dockerfile
    ports:
      - "5002:8080"
    depends_on:
      - db-user
  db-weight:
    image: mongo:8.0.3
    container_name: dbweight
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Oganesson123
    volumes:
      - ../mongo_weight:/data/db
  db-user:
    image: mongo:8.0.3
    container_name: dbuser
    ports:
      - "27019:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Oganesson123
    volumes:
      - ../mongo_user:/data/db
volumes:
  mongo_weight:
  mongo_user:  